services:
  easytech-site:
    build: .
    container_name: easytech-site
    restart: unless-stopped
    networks:
      - webproxy
    env_file:
      - .env

networks:
  webproxy:
    external: true
